spring:
  profiles:
    active: dev
  config:
    import: env.properties, optional:configserver:http://localhost:8888
  application:
    name: sleep-not-included-comment
  datasource:
    url: jdbc:postgresql://localhost:5432/sleep-not-included-comment
    username: ${PSQL_USERNAME}
    password: ${PSQL_PASSWORD}
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
sni:
  message: "test"
server:
  port: 8083
  servlet:
    context-path: /api/v1/
