spring:
  config:
    import: env.properties
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RawSaurus/sni-config
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          search-paths: https://github.com/RawSaurus/sni-config
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "busrefresh"
server:
  port: 8888
