#scrape_configs:
#  - job_name: 'sleep-not-included-user'
#    metrics_path: '/api/v1/actuator/prometheus'
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['host.docker.internal:8081']
#        labels:
#          application: 'sleep-not-included-user'
#  - job_name: 'sleep-not-included-user'
#    metrics_path: '/api/v1/actuator/prometheus'
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['host.docker.internal:8081']
#        labels:
#          application: 'sleep-not-included-user'

scrape_configs:
  - job_name: "eureka"
    eureka_sd_configs:
      - server: http://eureka:8761/eureka
    metrics_path: /actuator/prometheus
    relabel_configs:
      - source_labels: [__meta_eureka_sleep_not_included]
        target_label: application