scrape_configs:
  - job_name: 'sleep-not-included-user'
    metrics_path: '/api/v1/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8081']
        labels:
          application: 'sleep-not-included-user'