spring:
  profiles:
    active: dev
  config:
    import: env.properties, optional:configserver:http://localhost:8888
  application:
    name: sleep-not-included-user
  datasource:
    url: jdbc:postgresql://localhost:5432/sleep-not-included-user
    username: ${PSQL_USERNAME}
    password: ${PSQL_PASSWORD}
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
sni:
  message: "test"
logging:
  level:
    root: INFO
    com.rawsaurus.sleep_not_included.user: TRACE
  file:
    name: logs/user.log
server:
  port: 8081
  servlet:
    context-path: /api/v1/
