spring:
  config:
    import: env.properties
  application:
    name: sleep-not-included.build
  datasource:
    url: jdbc:postgresql://localhost:5432/sleep-not-included-build
    username: ${PSQL_USERNAME}
    password: ${PSQL_PASSWORD}
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082
  servlet:
    context-path: /api/v1/
